// Hata yonetimi icin Try Catch Kullanımı

let producs;

try{
    producs.forEach(item =>console.log(item));
} catch(error){
console.log("error;", error)
// producs = [1, 2, 3]
// producs.forEach(item => console.log(item))
}





console.log("Hata Yonetimi Duzgun Calışıyor")

let info = "Kodluyoruz"
console.log(info)